version: '3.7'
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
  web:
    build: .
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/firescrum
      - APP_ENV=prod
    ports:
      - '80:80'
